// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX37Q4edN65nrrcefwhhzfHgy26Hhsi0s',
    appId: '1:308332286849:web:8744b0524b1264f1744e80',
    messagingSenderId: '308332286849',
    projectId: 'pwsmt-fd851',
    authDomain: 'pwsmt-fd851.firebaseapp.com',
    storageBucket: 'pwsmt-fd851.firebasestorage.app',
    measurementId: 'G-DXQMGG0943',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDexuAkaG7uXbyf-YaBOvNNiVuxwP2hewE',
    appId: '1:308332286849:android:cee2703cb9ccc4b8744e80',
    messagingSenderId: '308332286849',
    projectId: 'pwsmt-fd851',
    storageBucket: 'pwsmt-fd851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl57bAX9_egYe6a3q4ZW5nP3aMUEFuA6w',
    appId: '1:308332286849:ios:0c34a050f4747298744e80',
    messagingSenderId: '308332286849',
    projectId: 'pwsmt-fd851',
    storageBucket: 'pwsmt-fd851.firebasestorage.app',
    androidClientId: '308332286849-3k9g3ctdfebaj8mh56p7619lgococd03.apps.googleusercontent.com',
    iosClientId: '308332286849-irnt6u02lpvht2k3987i28vahs623lqd.apps.googleusercontent.com',
    iosBundleId: 'com.MaxTristan.fFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl57bAX9_egYe6a3q4ZW5nP3aMUEFuA6w',
    appId: '1:308332286849:ios:b3b92f6467819ee0744e80',
    messagingSenderId: '308332286849',
    projectId: 'pwsmt-fd851',
    storageBucket: 'pwsmt-fd851.firebasestorage.app',
    androidClientId: '308332286849-3k9g3ctdfebaj8mh56p7619lgococd03.apps.googleusercontent.com',
    iosClientId: '308332286849-ularsmkjhqbv2f1e50qh00sjq6227r5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.fFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX37Q4edN65nrrcefwhhzfHgy26Hhsi0s',
    appId: '1:308332286849:web:8744b0524b1264f1744e80',
    messagingSenderId: '308332286849',
    projectId: 'pwsmt-fd851',
    authDomain: 'pwsmt-fd851.firebaseapp.com',
    storageBucket: 'pwsmt-fd851.firebasestorage.app',
    measurementId: 'G-DXQMGG0943',
  );

}